# Only if we can get sacct access working on cluster
defaults:
  - submitit_slurm

# @package hydra.launcher
submitit_folder: "${hydra.sweep.dir}/.submitit/%j"
timeout_min: 1440
cpus_per_task: 4
mem_gb: 8
nodes: 1
name: ${hydra.job.name}
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
partition: "jag-standard"
gres: "gpu:1"
